# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessmenttype', models.SmallIntegerField(choices=[(1, '\u4fe1\u606f\u7cfb\u7edf\u5b89\u5168\u7b49\u7ea7\u4fdd\u62a4\u57fa\u672c\u8981\u6c42')], default=1)),
                ('level', models.SmallIntegerField(choices=[(1, '\u7b2c\u4e00\u7ea7'), (2, '\u7b2c\u4e8c\u7ea7'), (3, '\u7b2c\u4e09\u7ea7'), (4, '\u7b2c\u56db\u7ea7'), (5, '\u7b2c\u4e94\u7ea7')])),
                ('Requirement', models.SmallIntegerField(choices=[(0, ''), (1, '\u6280\u672f\u8981\u6c42'), (2, '\u7ba1\u7406\u8981\u6c42')], default=1, null=True)),
                ('datatype', models.SmallIntegerField(choices=[(1, '\u7269\u7406\u5b89\u5168'), (2, '\u7f51\u7edc\u5b89\u5168'), (3, '\u4e3b\u673a\u5b89\u5168'), (4, '\u5e94\u7528\u5b89\u5168'), (5, '\u6570\u636e\u5b89\u5168\u53ca\u5907\u4efd\u6062\u590d'), (6, '\u5b89\u5168\u7ba1\u7406\u5236\u5ea6'), (7, '\u5b89\u5168\u7ba1\u7406\u673a\u6784'), (8, '\u4eba\u5458\u5b89\u5168\u7ba1\u7406'), (9, '\u7cfb\u7edf\u5efa\u8bbe\u7ba1\u7406'), (10, '\u7cfb\u7edf\u8fd0\u7ef4\u7ba1\u7406')])),
                ('match', models.SmallIntegerField(blank=True, choices=[(1, '\u5b8c\u5168\u7b26\u5408'), (2, '\u7b26\u5408'), (3, '\u90e8\u5206\u7b26\u5408'), (4, '\u5c11\u6570\u7b26\u5408'), (5, '\u4e0d\u7b26\u5408')], null=True)),
                ('generatetime', models.DateTimeField()),
            ],
            options={
                'ordering': ('datatype',),
                'db_table': 'Assessment_table',
                'verbose_name_plural': '\u8bc4\u4f30\u8868',
            },
        ),
        migrations.CreateModel(
            name='Data_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessmenttype', models.SmallIntegerField(choices=[(1, '\u4fe1\u606f\u7cfb\u7edf\u5b89\u5168\u7b49\u7ea7\u4fdd\u62a4\u57fa\u672c\u8981\u6c42')], default=1)),
                ('level', models.SmallIntegerField(choices=[(1, '\u7b2c\u4e00\u7ea7'), (2, '\u7b2c\u4e8c\u7ea7'), (3, '\u7b2c\u4e09\u7ea7'), (4, '\u7b2c\u56db\u7ea7'), (5, '\u7b2c\u4e94\u7ea7')])),
                ('Requirement', models.SmallIntegerField(choices=[(0, ''), (1, '\u6280\u672f\u8981\u6c42'), (2, '\u7ba1\u7406\u8981\u6c42')], null=True)),
                ('datatype', models.SmallIntegerField(choices=[(1, '\u7269\u7406\u5b89\u5168'), (2, '\u7f51\u7edc\u5b89\u5168'), (3, '\u4e3b\u673a\u5b89\u5168'), (4, '\u5e94\u7528\u5b89\u5168'), (5, '\u6570\u636e\u5b89\u5168\u53ca\u5907\u4efd\u6062\u590d'), (6, '\u5b89\u5168\u7ba1\u7406\u5236\u5ea6'), (7, '\u5b89\u5168\u7ba1\u7406\u673a\u6784'), (8, '\u4eba\u5458\u5b89\u5168\u7ba1\u7406'), (9, '\u7cfb\u7edf\u5efa\u8bbe\u7ba1\u7406'), (10, '\u7cfb\u7edf\u8fd0\u7ef4\u7ba1\u7406')])),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('-Assessmenttype',),
                'db_table': 'Data_table',
                'verbose_name_plural': '\u6570\u636e\u8868',
            },
        ),
        migrations.CreateModel(
            name='Project_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=40)),
                ('Assessmenttype', models.SmallIntegerField(choices=[(1, '\u4fe1\u606f\u7cfb\u7edf\u5b89\u5168\u7b49\u7ea7\u4fdd\u62a4\u57fa\u672c\u8981\u6c42')], default=1)),
                ('level', models.SmallIntegerField(choices=[(1, '\u7b2c\u4e00\u7ea7'), (2, '\u7b2c\u4e8c\u7ea7'), (3, '\u7b2c\u4e09\u7ea7'), (4, '\u7b2c\u56db\u7ea7'), (5, '\u7b2c\u4e94\u7ea7')])),
                ('generatetime', models.DateTimeField()),
            ],
            options={
                'ordering': ('-generatetime',),
                'db_table': 'Project_table',
                'verbose_name_plural': '\u9879\u76ee\u8868',
            },
        ),
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=18)),
                ('password', models.CharField(max_length=88)),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=42)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('generatetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_table',
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
        migrations.AddField(
            model_name='project_table',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='assessproject.User_table'),
        ),
        migrations.AddField(
            model_name='assessment_table',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessproject.Data_table'),
        ),
        migrations.AddField(
            model_name='assessment_table',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessproject.Project_table'),
        ),
        migrations.AddField(
            model_name='assessment_table',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='assessproject.User_table'),
        ),
        migrations.AlterUniqueTogether(
            name='project_table',
            unique_together=set([('projectname', 'username')]),
        ),
    ]
