# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=60, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessproject.Project_table')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='assessproject.User_table')),
            ],
            options={
                'db_table': 'File_table',
                'verbose_name_plural': '\u6587\u4ef6\u8868',
            },
        ),
    ]
