# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessproject', '0002_file_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_table',
            name='file',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
